AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'temp/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'package.json'
    - 'Rakefile'
    - 'README.md'
    - 'yarn.lock'

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
